/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.jianzhao.sugar;

import org.junit.jupiter.api.Test;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import static java.nio.charset.StandardCharsets.UTF_8;
import static org.jianzhao.sugar.Sugar.use;
import static org.jianzhao.sugar.Sugar.with;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertIterableEquals;

class SugarTest {

    @Test
    public void testUse() throws IOException {
        byte[] origin = {104, 101, 108, 108, 111, 32, 65, 100, 97};
        var in = new ByteArrayInputStream(origin);
        var s = use(in, it -> new String(it.readAllBytes(), UTF_8));
        assertEquals("hello Ada", s);
    }

    @Test
    public void testWith() {
        var list = new ArrayList<>(List.of(1, 2, 3));
        with(list, Collections::reverse);
        assertIterableEquals(List.of(3, 2, 1), list);
    }
}
